$(document).ready(function () {
    $("#region").change(function () {
        var val = $(this).val();
        if (val == "north") {
            $("#size").html("<option value='test'>Select a district</option><option value='abim'>Abim</option><option value='adjumani'>Adjumani</option><option value='agago'>Agago</option><option value='alebtong'>Alebtong</option><option value='amolata'>Amolatar</option><option value='amudat'>Amudat</option><option value='abim'>Abim</option><option value='adjumani'>Adjumani</option><option value='agago'>Agago</option><option value='alebtong'>Alebtong</option><option value='amolatar'>Amolatar</option><option value='amudat'>Amudat</option><option value='amuru'>Amuru</option><option value='apac'>Apac</option><option value='arua'>Arua</option><option value='dokolo'>Dokolo</option><option value='gulu'>Gulu</option><option value='kaabong'>Kaabong</option><option value='kitgum'>Kitgum</option><option value='koboko'>Koboko</option><option value='kole'>Kole</option><option value='kotido'>Kotido</option><option value='lamwo'>Lamwo</option><option value='lira'>Lira</option><option value='maracha'>Maracha</option><option value='moroto'>Moroto</option><option value='moyo'>Moyo</option><option value='nakapiripiriti'>Nakapiripirit</option><option value='nebbi'>Nebbi</option><option value='nwoya'>Nwoya</option><option value='otuke'>Otuke</option><option value='oyam'>Oyam</option><option value='pader'>Pader</option><option value='yumbe'>Yumbe</option><option value='zombo'>Zombo</option>");
        } else if (val == "west") {
            $("#size").html("<option value='test'>Select a district</option><option value='buhweju'>Buhweju</option><option value='buliisa'>Buliisa</option><option value='bundibugyo'>Bundibugyo</option><option value='bushenyi'>Bushenyi</option><option value='hoima'>Hoima</option><option value='ibanda'>Ibanda</option><option value='isingiro'>Isingiro</option><option value='kabale'>Kabale</option><option value='kabarole'>Kabarole</option><option value='kamwenge'>Kamwenge</option><option value='kanungu'>Kanungu</option><option value='kasese'>Kasese</option><option value='kibaale'>Kibaale</option><option value='kiruhura'>Kiruhura</option><option value='kiryandongo'>Kiryandongo</option><option value='kisoro'>Kisoro</option><option value='kyegegwa'>Kyegegwa</option><option value='kyenjojo'>Kyenjojo</option><option value='masindi'>Masindi</option><option value='mbarara'>Mbarara</option><option value='mitooma'>Mitooma</option><option value='ntoroko'>Ntoroko</option><option value='ntungamo'>Ntungamo</option><option value='rubirizi'>Rubirizi</option><option value='rukkungiri'>Rukungiri</option><option value='Sheema'>Sheema</option>");
        } else if (val == "east") {
            $("#size").html("<option value='test'>Select a district</option><option value='amuria'>Amuria</option><option value='budaka'>Budaka</option><option value='bududa'>Bududa</option><option value='bugiri'>Bugiri</option><option value='bukedea'>Bukedea</option><option value='bukwa'>Bukwa</option><option value='bulambuli'>Bulambuli</option><option value='busia'>Busia</option><option value='butaleja'>Butaleja</option><option value='buyende'>Buyende</option><option value='iganga'>Iganga</option><option value='jinja'>Jinja</option><option value='kaberamaido'>Kaberamaido</option><option value='kaliro'>Kaliro</option><option value='kamuli'>Kamuli</option><option value='kapchorwa'>Kapchorwa</option><option value='katakwi'>Katakwi</option><option value='kibuku'>Kibuku</option><option value='kumi'>Kumi</option><option value='kween'>Kween</option><option value='luuka'>Luuka</option><option value='manafwa'>Manafwa</option><option value='mayuge'>Mayuge</option><option value='mbale'>Mbale</option><option value='namayingo'>Namayingo</option><option value='namutumba'>Namutumba</option><option value='ngoro'>Ngora</option><option value='pallisi'>Pallisa</option><option value='serere'>Serere</option><option value='sironko'>Sironko</option><option value='soroti'>Soroti</option><option value='tororo'>Tororo</option>");
        }
          else if (val == "central") {
            $("#size").html("<option value='test'>Select a district</option><option value='buikwe'>Buikwe</option><option value='bukomansimbi'>Bukomansimbi</option><option value='butambala'>Butambala</option><option value='buvuma'>Buvuma</option><option value='gomba'>Gomba</option><option value='kalangala'>Kalangala</option><option value='kalungu'>Kalungu</option><option value='kampala'>Kampala</option><option value='kayunga'>Kayunga</option><option value='kiboga'>Kiboga</option><option value='kyankwanzi'>Kyankwanzi</option><option value='luweero'>Luweero</option><option value='lwengo'>Lwengo</option><option value='lyantonde'>Lyantonde</option><option value='masaka'>Masaka</option><option value='mityana'>Mityana</option><option value='mpigi'>Mpigi</option><option value='mubende'>Mubende</option><option value='mukono'>Mukono</option><option value='nakaseke'>Nakaseke</option><option value='nakasongolo'>Nakasongola</option><option value='rakai'>Rakai</option><option value='ssembabule'>Ssembabule</option><option value='mubende'>Mubende</option><option value='wakiso'>Wakiso</option>");
        }
		else if (val == "item0") {
            $("#size").html("<option value='test'>Select a district</option>");
        }
    });
});